version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: learnphp-app
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
  nginx: 
    image: nginx:latest
    container_name: learnphp-nginx
    restart: always
    ports: 
     - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d